/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS  %W% --- %G% -- %U% */

/*BasalGanglia
* BasalGanglia
* @see BasalGanglia.nslm
* @version 98/6/18
* @author Dominey and Alexander
*
*/
 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

 public class BasalGanglia extends NslModule /*(int stdsz)*/  {
// port inputs
public NslDinFloat2 fefmem ; /*(stdsz,stdsz)*/
public NslDinFloat2 fefsac ; /*(stdsz,stdsz)*/
// port outputs
public NslDoutFloat2 snrmem ; /*(stdsz,stdsz)*/
public NslDoutFloat2 snrsac ; /*(stdsz,stdsz)*/
// parameters 
//vars
private Caudate cd ; /*(stdsz)*/
private SNR snr ; /*(stdsz)*/

public  void makeConn() {
	nslConnect(fefsac,cd.fefsac);
	nslConnect(fefmem,cd.fefmem);
	nslConnect(cd.cdsac,snr.cdsac);
	nslConnect(cd.cdmem,snr.cdmem);
	nslConnect(snr.snrsac,snrsac);
	nslConnect(snr.snrmem,snrmem);
}

public  void simRun() {
	if (system.debug>=21) {
		System.out.println("BG: simRun");
	}
}

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */
	int stdsz;

	 /*GENERIC CONSTRUCTOR:   */
	 public BasalGanglia(String nslName, NslModule nslParent,int stdsz) {
		super(nslName, nslParent);
		this.stdsz = stdsz;
		initSys();
		makeInst(nslName, nslParent,stdsz);
	}
	public void makeInst(String nslName, NslModule nslParent,int stdsz){ 
	 fefmem=new NslDinFloat2 ("fefmem",this,stdsz,stdsz); //NSLDECLS 
	 fefsac=new NslDinFloat2 ("fefsac",this,stdsz,stdsz); //NSLDECLS 
	 snrmem=new NslDoutFloat2 ("snrmem",this,stdsz,stdsz); //NSLDECLS 
	 snrsac=new NslDoutFloat2 ("snrsac",this,stdsz,stdsz); //NSLDECLS 
	 cd=new Caudate ("cd",this,stdsz); //NSLDECLS 
	 snr=new SNR ("snr",this,stdsz); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
