/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS  %W% --- %G% -- %U% */

/*Erasure2
* Erasure2 Mask  - was called M2 in NSL2.1.7 version
* @see Erasure2.nslm
* @version 98/6/18
* @author Dominey and Alexander
*
*/

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

 public class Erasure2 extends NslModule /*(int stdsz)*/  {
// port inputs
// port outputs
public NslDoutFloat2 erasure2 ; /*(stdsz,stdsz)*/

// parameters 
//vars
 int 	halfStdsz=0;
 int	oneThirdStdsz=0;
 int	twoThirdsStdszMin1=0;


public  void initModule() {	
	halfStdsz=(int)stdsz/2;  // if stdsz=9, then this is 4
	oneThirdStdsz=(int)stdsz/3;  //if stdsz=9, then this is 3
	twoThirdsStdszMin1=oneThirdStdsz+ oneThirdStdsz-1; //if, then 5
}

public  void initRun() {
	// the following draws a square outlining the fovea
	// with 1 everywhere except the outline which is 0.5
	erasure2.set(1);       // set everything to 1 then set some to 0.5                    
	(erasure2).set(oneThirdStdsz,oneThirdStdsz,.5);
	(erasure2).set(oneThirdStdsz,halfStdsz,0.5); 
	(erasure2).set(oneThirdStdsz,twoThirdsStdszMin1,0.5);

	(erasure2).set(halfStdsz,oneThirdStdsz,0.5);
	(erasure2).set(halfStdsz,halfStdsz,0.5); 
	(erasure2).set(halfStdsz,twoThirdsStdszMin1,0.5);

	(erasure2).set(twoThirdsStdszMin1,oneThirdStdsz,0.5);
	(erasure2).set(twoThirdsStdszMin1,halfStdsz,0.5); 
	(erasure2).set(twoThirdsStdszMin1,twoThirdsStdszMin1,0.5);

	if (system.debug>1) {
		System.out.println("Erasure2:initRun: erasure2");
		System.out.println(erasure2);
	}
}

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */
	int stdsz;

	 /*GENERIC CONSTRUCTOR:   */
	 public Erasure2(String nslName, NslModule nslParent,int stdsz) {
		super(nslName, nslParent);
		this.stdsz = stdsz;
		initSys();
		makeInst(nslName, nslParent,stdsz);
	}
	public void makeInst(String nslName, NslModule nslParent,int stdsz){ 
	 erasure2=new NslDoutFloat2 ("erasure2",this,stdsz,stdsz); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
