/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS  %W% --- %G% -- %U% */

/*MN
* Motor Neurons
* @see MN.nslm
* @version 98/6/18
* @author Dominey ; coder Alexander
*
*/
 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

 public class MN extends NslModule /*()*/  {

// ports
public NslDinFloat0 ebn ; /* ()*/
public NslDinFloat0 tn ; /* ()*/
public NslDoutFloat0 mn ; /*  ()*/
// parameters 

//vars


public  void initRun() {
	mn.set(0);
}

public  void simRun() {
	mn.set(
 nslj.src.math.NslAdd.eval(ebn.get(),tn.get()));

	if (system.debug>=11) {
		System.out.println(("MN:simRun:mn")+(mn));
	}
}
	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */

	 /*GENERIC CONSTRUCTOR:   */
	 public MN(String nslName, NslModule nslParent) {
		super(nslName, nslParent);
		initSys();
		makeInst(nslName, nslParent);
	}
	public void makeInst(String nslName, NslModule nslParent){ 
	 ebn=new NslDinFloat0 ("ebn",this); //NSLDECLS 
	 tn=new NslDinFloat0 ("tn",this); //NSLDECLS 
	 mn=new NslDoutFloat0 ("mn",this); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
