/* Generated By:JJTree: Do not edit this line. NslParserVisitor.java */

public interface NslParserVisitor {
    Object visit(SimpleNode node, Object data);

    Object visit(ASTNslImportDeclaration node, Object data);

    Object visit(ASTNslClassDeclaration node, Object data);

    Object visit(ASTNslNestedClassDeclaration node, Object data);

    Object visit(ASTNslFieldDeclaration node, Object data);

    Object visit(ASTNslLocalVariableDeclaration node, Object data);

    Object visit(ASTNslVariableDeclarator node, Object data);

    Object visit(ASTNslArrayDeclarator node, Object data);

    Object visit(ASTCompilationUnit node, Object data);

    Object visit(ASTPackageDeclaration node, Object data);

    Object visit(ASTImportDeclaration node, Object data);

    Object visit(ASTTypeDeclaration node, Object data);

    Object visit(ASTClassDeclaration node, Object data);

    Object visit(ASTUnmodifiedClassDeclaration node, Object data);

    Object visit(ASTClassBody node, Object data);

    Object visit(ASTNestedClassDeclaration node, Object data);

    Object visit(ASTClassBodyDeclaration node, Object data);

    Object visit(ASTMethodDeclarationLookahead node, Object data);

    Object visit(ASTInterfaceDeclaration node, Object data);

    Object visit(ASTNestedInterfaceDeclaration node, Object data);

    Object visit(ASTUnmodifiedInterfaceDeclaration node, Object data);

    Object visit(ASTInterfaceMemberDeclaration node, Object data);

    Object visit(ASTFieldDeclaration node, Object data);

    Object visit(ASTVariableDeclarator node, Object data);

    Object visit(ASTVariableDeclaratorId node, Object data);

    Object visit(ASTVariableInitializer node, Object data);

    Object visit(ASTArrayInitializer node, Object data);

    Object visit(ASTMethodDeclaration node, Object data);

    Object visit(ASTMethodDeclarator node, Object data);

    Object visit(ASTFormalParameters node, Object data);

    Object visit(ASTFormalParameter node, Object data);

    Object visit(ASTConstructorDeclaration node, Object data);

    Object visit(ASTExplicitConstructorInvocation node, Object data);

    Object visit(ASTInitializer node, Object data);

    Object visit(ASTType node, Object data);

    Object visit(ASTPrimitiveType node, Object data);

    Object visit(ASTResultType node, Object data);

    Object visit(ASTName node, Object data);

    Object visit(ASTNameList node, Object data);

    Object visit(ASTExpression node, Object data);

    Object visit(ASTAssignmentOperator node, Object data);

    Object visit(ASTConditionalExpression node, Object data);

    Object visit(ASTConditionalOrExpression node, Object data);

    Object visit(ASTConditionalAndExpression node, Object data);

    Object visit(ASTInclusiveOrExpression node, Object data);

    Object visit(ASTExclusiveOrExpression node, Object data);

    Object visit(ASTAndExpression node, Object data);

    Object visit(ASTEqualityExpression node, Object data);

    Object visit(ASTInstanceOfExpression node, Object data);

    Object visit(ASTRelationalExpression node, Object data);

    Object visit(ASTShiftExpression node, Object data);

    Object visit(ASTAdditiveExpression node, Object data);

    Object visit(ASTMultiplicativeExpression node, Object data);

    Object visit(ASTUnaryExpression node, Object data);

    Object visit(ASTPreIncrementExpression node, Object data);

    Object visit(ASTPreDecrementExpression node, Object data);

    Object visit(ASTUnaryExpressionNotPlusMinus node, Object data);

    Object visit(ASTCastLookahead node, Object data);

    Object visit(ASTPostfixExpression node, Object data);

    Object visit(ASTCastExpression node, Object data);

    Object visit(ASTPrimaryExpression node, Object data);

    Object visit(ASTPrimaryPrefix node, Object data);

    Object visit(ASTPrimarySuffix node, Object data);

    Object visit(ASTLiteral node, Object data);

    Object visit(ASTBooleanLiteral node, Object data);

    Object visit(ASTNullLiteral node, Object data);

    Object visit(ASTArguments node, Object data);

    Object visit(ASTArgumentList node, Object data);

    Object visit(ASTAllocationExpression node, Object data);

    Object visit(ASTArrayDimsAndInits node, Object data);

    Object visit(ASTStatement node, Object data);

    Object visit(ASTLabeledStatement node, Object data);

    Object visit(ASTBlock node, Object data);

    Object visit(ASTBlockStatement node, Object data);

    Object visit(ASTLocalVariableDeclaration node, Object data);

    Object visit(ASTEmptyStatement node, Object data);

    Object visit(ASTStatementExpression node, Object data);

    Object visit(ASTSwitchStatement node, Object data);

    Object visit(ASTSwitchLabel node, Object data);

    Object visit(ASTIfStatement node, Object data);

    Object visit(ASTWhileStatement node, Object data);

    Object visit(ASTDoStatement node, Object data);

    Object visit(ASTForStatement node, Object data);

    Object visit(ASTForInit node, Object data);

    Object visit(ASTStatementExpressionList node, Object data);

    Object visit(ASTForUpdate node, Object data);

    Object visit(ASTBreakStatement node, Object data);

    Object visit(ASTContinueStatement node, Object data);

    Object visit(ASTReturnStatement node, Object data);

    Object visit(ASTThrowStatement node, Object data);

    Object visit(ASTSynchronizedStatement node, Object data);

    Object visit(ASTTryStatement node, Object data);

    Object visit(ASTAssertStatement node, Object data);

    Object visit(ASTerror_skipto node, Object data);
}
