/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS  %W%---%G%--%U% */
/* old kversion @(#)CDlatinh.mod	1.8 --- 08/05/99 -- 13:56:07 : jversion  @(#)CDlatinh.mod	1.2---04/23/99--18:39:20 */
// Import statements
 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

// Leaf nodes

//
// CDlatinh
//
/**
 * CDlatinh class
 * Represents the Caudate Non-dopaminergic Interneuron Cells Layer
 * @see     CDlatinh
 * @version 0.1 96/11/19
 * @author  Michael Crowley
 * @var public PFCgo_in - input coming from PFC module (of type NslDouble2)<p>
 * @var public FEFsac_in - input coming from FEF module (of type NslDouble2)<p>
 * @var public CDlatinh_out - output going to CDlattan module (of type NslDouble2)<p>
 */
/*---*/

 public class CDlatinh extends NslModule/*(int CorticalArraySize)*/  {
  public NslDinDouble2 FEFsac_in ; /*(CorticalArraySize,CorticalArraySize)*/
  public NslDinDouble2 PFCgo_in ; /*(CorticalArraySize,CorticalArraySize)*/
  public NslDoutDouble2 CDlatinh_out ; /*(CorticalArraySize,CorticalArraySize)*/

  // private variables

  private NslDouble2 cdlatinh ; /*(CorticalArraySize,CorticalArraySize)*/

  private  double cdlatinhtm;
  private  double CDlisigma1;
  private  double CDlisigma2;
  private  double CDlisigma3;
  private  double CDlisigma4;
 

public  void initRun () {
    CDlatinh_out.set(0);
    cdlatinhtm = 0.01;
    CDlisigma1 = 45;
    CDlisigma2 = 90;
    CDlisigma3 = 0;
    CDlisigma4 = 20; // 60;
}
public  void simRun () {
  // System.err.println("@@@@ CDlatinh simRun entered @@@@");
    cdlatinh.set(system.nsldiff.eval(cdlatinh,cdlatinhtm,
 __nsltmp103=nslj.src.math.NslAdd.eval(__nsltmp103,
 __nsltmp102=nslj.src.math.NslAdd.eval(__nsltmp102,
 __nsltmp101=nslj.src.math.NslSub.eval(__nsltmp101,0,cdlatinh.get()),FEFsac_in.get()),PFCgo_in.get()))) /* rule 108 */;
    CDlatinh_out.set(Nsl2Sigmoid.eval(cdlatinh,CDlisigma1,CDlisigma2,CDlisigma3,CDlisigma4)) /* rule 108 */;
}



	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	__nsltmp101 = new double[1][1];
	__nsltmp102 = new double[1][1];
	__nsltmp103 = new double[1][1];
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	for (int i = 0; i < __nsltmp101.length; i++) {
		for (int j = 0; j < __nsltmp101[0].length; j++) {
			__nsltmp101[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp102.length; i++) {
		for (int j = 0; j < __nsltmp102[0].length; j++) {
			__nsltmp102[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp103.length; i++) {
		for (int j = 0; j < __nsltmp103[0].length; j++) {
			__nsltmp103[i][j] = 0;
		}
	}
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	private  double[][] __nsltmp101;
	private  double[][] __nsltmp102;
	private  double[][] __nsltmp103;
	/* constructor and related methods */
	/* nsl declarations */
	int CorticalArraySize;

	 /*GENERIC CONSTRUCTOR:   */
	 public CDlatinh(String nslName, NslModule nslParent,int CorticalArraySize) {
		super(nslName, nslParent);
		this.CorticalArraySize = CorticalArraySize;
		initSys();
		makeInst(nslName, nslParent,CorticalArraySize);
	}
	public void makeInst(String nslName, NslModule nslParent,int CorticalArraySize){ 
	 FEFsac_in=new NslDinDouble2 ("FEFsac_in",this,CorticalArraySize,CorticalArraySize); //NSLDECLS 
	 PFCgo_in=new NslDinDouble2 ("PFCgo_in",this,CorticalArraySize,CorticalArraySize); //NSLDECLS 
	 CDlatinh_out=new NslDoutDouble2 ("CDlatinh_out",this,CorticalArraySize,CorticalArraySize); //NSLDECLS 
	 cdlatinh=new NslDouble2 ("cdlatinh",this,CorticalArraySize,CorticalArraySize); //NSLDECLS 
	}
	/* end of automatic declaration statements */
} //end class
