/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS  %W%---%G%--%U% */
/* old kversion @(#)MedBulk.mod	1.8 --- 08/05/99 -- 13:56:28 : jversion  @(#)MedBulk.mod	1.2---04/23/99--18:39:36 */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

/////////////////////////////////////////////
//Module: MedBulk - Part of the Thalamus
/////////////////////////////////////////////

//
//MedBulk
//
 public class MedBulk extends NslModule/*(int CorticalArraySize, int MaxConnections)*/ {

// output ports

    public NslDoutInt2 SNRMapCount_bulk ; /* (CorticalArraySize,CorticalArraySize)*/

    public NslDoutDouble3 SNRweights_bulk ; /* (CorticalArraySize,CorticalArraySize,MaxConnections)*/

    public NslDoutInt3 SNRxmap_bulk ; /* (CorticalArraySize,CorticalArraySize,MaxConnections)*/
    public NslDoutInt3 SNRymap_bulk ; /* (CorticalArraySize,CorticalArraySize,MaxConnections)*/

    public NslDoutInt3 FEFxmap_bulk ; /* (CorticalArraySize,CorticalArraySize,MaxConnections)*/
    public NslDoutInt3 FEFymap_bulk ; /* (CorticalArraySize,CorticalArraySize,MaxConnections)*/
    public NslDoutInt3 LIPxmap_bulk ; /* (CorticalArraySize,CorticalArraySize,MaxConnections)*/
    public NslDoutInt3 LIPymap_bulk ; /* (CorticalArraySize,CorticalArraySize,MaxConnections)*/
    public NslDoutInt3 PFCxmap_bulk ; /* (CorticalArraySize,CorticalArraySize,MaxConnections)*/
    public NslDoutInt3 PFCymap_bulk ; /* (CorticalArraySize,CorticalArraySize,MaxConnections)*/

  public  void initRun()
  {
    SNRMapCount_bulk.set(0);
    SNRweights_bulk.set(0);
    SNRxmap_bulk.set(0);
    SNRymap_bulk.set(0);
    FEFxmap_bulk.set(0);
    FEFymap_bulk.set(0);
    LIPxmap_bulk.set(0);
    LIPymap_bulk.set(0);
    PFCxmap_bulk.set(0);
    PFCymap_bulk.set(0);
  }

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */
	int CorticalArraySize;
	int MaxConnections;

	 /*GENERIC CONSTRUCTOR:   */
	 public MedBulk(String nslName, NslModule nslParent,int CorticalArraySize, int MaxConnections) {
		super(nslName, nslParent);
		this.CorticalArraySize = CorticalArraySize;
		this.MaxConnections = MaxConnections;
		initSys();
		makeInst(nslName, nslParent,CorticalArraySize, MaxConnections);
	}
	public void makeInst(String nslName, NslModule nslParent,int CorticalArraySize,int MaxConnections){ 
	 SNRMapCount_bulk=new NslDoutInt2 ("SNRMapCount_bulk",this,CorticalArraySize,CorticalArraySize); //NSLDECLS 
	 SNRweights_bulk=new NslDoutDouble3 ("SNRweights_bulk",this,CorticalArraySize,CorticalArraySize,MaxConnections); //NSLDECLS 
	 SNRxmap_bulk=new NslDoutInt3 ("SNRxmap_bulk",this,CorticalArraySize,CorticalArraySize,MaxConnections); //NSLDECLS 
	 SNRymap_bulk=new NslDoutInt3 ("SNRymap_bulk",this,CorticalArraySize,CorticalArraySize,MaxConnections); //NSLDECLS 
	 FEFxmap_bulk=new NslDoutInt3 ("FEFxmap_bulk",this,CorticalArraySize,CorticalArraySize,MaxConnections); //NSLDECLS 
	 FEFymap_bulk=new NslDoutInt3 ("FEFymap_bulk",this,CorticalArraySize,CorticalArraySize,MaxConnections); //NSLDECLS 
	 LIPxmap_bulk=new NslDoutInt3 ("LIPxmap_bulk",this,CorticalArraySize,CorticalArraySize,MaxConnections); //NSLDECLS 
	 LIPymap_bulk=new NslDoutInt3 ("LIPymap_bulk",this,CorticalArraySize,CorticalArraySize,MaxConnections); //NSLDECLS 
	 PFCxmap_bulk=new NslDoutInt3 ("PFCxmap_bulk",this,CorticalArraySize,CorticalArraySize,MaxConnections); //NSLDECLS 
	 PFCymap_bulk=new NslDoutInt3 ("PFCymap_bulk",this,CorticalArraySize,CorticalArraySize,MaxConnections); //NSLDECLS 
	}
	/* end of automatic declaration statements */
} //end class
