/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS  %W%---%G%--%U% */
/* old kversion @(#)PFCgo.mod	1.8 --- 08/05/99 -- 13:56:31 : jversion  @(#)PFCgo.mod	1.2---04/23/99--18:39:39 */
/* $lOG$ */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

//
// PFCgo
//
 public class PFCgo extends NslModule/*(int array_size)*/ {
   // input ports
    public NslDinDouble2 LIPmem_in ; /*(array_size,array_size)*/
    public NslDinDouble2 PFCseq_in ; /*(array_size,array_size)*/
    public NslDinDouble2 PFCfovea_in ; /*(array_size,array_size)*/
   // output ports
    public NslDoutDouble2 PFCgo_out ; /* (array_size,array_size)  */
    public NslDouble2 pfcgo ; /*(array_size,array_size)   */

  // private variables

  private  double           pfcgotm;
  private  double           basepfcgotm;
  private  double           CorticalSlowdown;
  private  double           PFCgosigma1;
  private  double           PFCgosigma2;
  private  double           PFCgosigma3;
  private  double           PFCgosigma4;
   static private  double PFCseqK=  0.9; 
   static private  double PFClipmem  =  0.35;
  
public  void initRun(){
//    PFClipmem      =  0.35; 
//    PFCseqK        =  0.9;

    pfcgo.set(0.0);
    PFCgo_out.set(0.0);
    basepfcgotm = 0.008;
    CorticalSlowdown = 1.0;
    pfcgotm = basepfcgotm * CorticalSlowdown;
    PFCgosigma1 = 20.0;
    PFCgosigma2 = 60.0;
    PFCgosigma3 = 0.0;
    PFCgosigma4 = 60.0;
}

public  void simRun(){

  // System.err.println("@@@@ PFCgo simRun entered @@@@");
    /* <Q> PFClipmem PFCseqK */
    pfcgo.set(system.nsldiff.eval(pfcgo,pfcgotm,
 __nsltmp106=nslj.src.math.NslSub.eval(__nsltmp106,
 __nsltmp105=nslj.src.math.NslAdd.eval(__nsltmp105,
 __nsltmp103=nslj.src.math.NslAdd.eval(__nsltmp103,
 __nsltmp101=nslj.src.math.NslSub.eval(__nsltmp101,0,pfcgo.get()),
 __nsltmp102=nslj.src.math.NslElemMult.eval(__nsltmp102,PFClipmem,LIPmem_in.get())),
 __nsltmp104=nslj.src.math.NslElemMult.eval(__nsltmp104,PFCseqK,PFCseq_in.get())),PFCfovea_in.get()))) /* rule 108 */;
    PFCgo_out.set(Nsl2Sigmoid.eval(pfcgo,PFCgosigma1,PFCgosigma2,PFCgosigma3,PFCgosigma4)) /* rule 108 */;
	// 96/12/20 aa
	//System.out.println("PFCgo_out: " + PFCgo_out);
  }

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	__nsltmp101 = new double[1][1];
	__nsltmp102 = new double[1][1];
	__nsltmp103 = new double[1][1];
	__nsltmp104 = new double[1][1];
	__nsltmp105 = new double[1][1];
	__nsltmp106 = new double[1][1];
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	for (int i = 0; i < __nsltmp101.length; i++) {
		for (int j = 0; j < __nsltmp101[0].length; j++) {
			__nsltmp101[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp102.length; i++) {
		for (int j = 0; j < __nsltmp102[0].length; j++) {
			__nsltmp102[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp103.length; i++) {
		for (int j = 0; j < __nsltmp103[0].length; j++) {
			__nsltmp103[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp104.length; i++) {
		for (int j = 0; j < __nsltmp104[0].length; j++) {
			__nsltmp104[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp105.length; i++) {
		for (int j = 0; j < __nsltmp105[0].length; j++) {
			__nsltmp105[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp106.length; i++) {
		for (int j = 0; j < __nsltmp106[0].length; j++) {
			__nsltmp106[i][j] = 0;
		}
	}
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	private  double[][] __nsltmp101;
	private  double[][] __nsltmp102;
	private  double[][] __nsltmp103;
	private  double[][] __nsltmp104;
	private  double[][] __nsltmp105;
	private  double[][] __nsltmp106;
	/* constructor and related methods */
	/* nsl declarations */
	int array_size;

	 /*GENERIC CONSTRUCTOR:   */
	 public PFCgo(String nslName, NslModule nslParent,int array_size) {
		super(nslName, nslParent);
		this.array_size = array_size;
		initSys();
		makeInst(nslName, nslParent,array_size);
	}
	public void makeInst(String nslName, NslModule nslParent,int array_size){ 
	 LIPmem_in=new NslDinDouble2 ("LIPmem_in",this,array_size,array_size); //NSLDECLS 
	 PFCseq_in=new NslDinDouble2 ("PFCseq_in",this,array_size,array_size); //NSLDECLS 
	 PFCfovea_in=new NslDinDouble2 ("PFCfovea_in",this,array_size,array_size); //NSLDECLS 
	 PFCgo_out=new NslDoutDouble2 ("PFCgo_out",this,array_size,array_size); //NSLDECLS 
	 pfcgo=new NslDouble2 ("pfcgo",this,array_size,array_size); //NSLDECLS 
	}
	/* end of automatic declaration statements */
} // end class
