/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS  %W%---%G%--%U% */
/* old kversion @(#)RNMEDinh.mod	1.8 --- 08/05/99 -- 13:56:33 : jversion  @(#)RNMEDinh.mod	1.2---04/23/99--18:39:41 */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

/**
* Module RNMEDinh - part of thalamus
*/
 public class RNMEDinh extends NslModule/*(int array_size)*/ {
	//inports
    public NslDinDouble2 SNRmedburst_in ; /*(array_size,array_size)  */
	//outports
    public NslDoutDouble2 RNMEDinh_out ; /*(array_size,array_size)  */

	// privates
    private NslDouble2 RNmedinh ; /* (array_size,array_size)   */
	private  double     RNmedinhtm;
	private  double     RNmedinhTONIC;
	private  double     RNmedinhK;
	private  double     RNmedinhsigma1;
	private  double     RNmedinhsigma2;
	private  double     RNmedinhsigma3;
	private  double     RNmedinhsigma4;


public  void initRun(){
    RNmedinh.set(0);
    RNMEDinh_out.set(0);
     RNmedinhtm=0.006;
     RNmedinhTONIC=10;
     RNmedinhK=0.16;
     RNmedinhsigma1=-10;
     RNmedinhsigma2=10;
     RNmedinhsigma3=0;
     RNmedinhsigma4=10;
}

public  void simRun() {
	  /* <Q> SNRmedburst_in */
  // System.err.println("@@@@ RNMEDinh simRun entered @@@@");
    RNmedinh.set(system.nsldiff.eval(RNmedinh,RNmedinhtm,
 __nsltmp104=nslj.src.math.NslSub.eval(__nsltmp104,
 __nsltmp102=nslj.src.math.NslAdd.eval(__nsltmp102,
 __nsltmp101=nslj.src.math.NslSub.eval(__nsltmp101,0,RNmedinh.get()),RNmedinhTONIC),
 __nsltmp103=nslj.src.math.NslElemMult.eval(__nsltmp103,RNmedinhK,SNRmedburst_in.get())))) /* rule 108 */;

    RNMEDinh_out.set(Nsl2Sigmoid.eval(RNmedinh,RNmedinhsigma1,RNmedinhsigma2,RNmedinhsigma3,RNmedinhsigma4)) /* rule 108 */;
  }

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	__nsltmp101 = new double[1][1];
	__nsltmp102 = new double[1][1];
	__nsltmp103 = new double[1][1];
	__nsltmp104 = new double[1][1];
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	for (int i = 0; i < __nsltmp101.length; i++) {
		for (int j = 0; j < __nsltmp101[0].length; j++) {
			__nsltmp101[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp102.length; i++) {
		for (int j = 0; j < __nsltmp102[0].length; j++) {
			__nsltmp102[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp103.length; i++) {
		for (int j = 0; j < __nsltmp103[0].length; j++) {
			__nsltmp103[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp104.length; i++) {
		for (int j = 0; j < __nsltmp104[0].length; j++) {
			__nsltmp104[i][j] = 0;
		}
	}
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	private  double[][] __nsltmp101;
	private  double[][] __nsltmp102;
	private  double[][] __nsltmp103;
	private  double[][] __nsltmp104;
	/* constructor and related methods */
	/* nsl declarations */
	int array_size;

	 /*GENERIC CONSTRUCTOR:   */
	 public RNMEDinh(String nslName, NslModule nslParent,int array_size) {
		super(nslName, nslParent);
		this.array_size = array_size;
		initSys();
		makeInst(nslName, nslParent,array_size);
	}
	public void makeInst(String nslName, NslModule nslParent,int array_size){ 
	 SNRmedburst_in=new NslDinDouble2 ("SNRmedburst_in",this,array_size,array_size); //NSLDECLS 
	 RNMEDinh_out=new NslDoutDouble2 ("RNMEDinh_out",this,array_size,array_size); //NSLDECLS 
	 RNmedinh=new NslDouble2 ("RNmedinh",this,array_size,array_size); //NSLDECLS 
	}
	/* end of automatic declaration statements */
} //end class
