/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS  %W%---%G%--%U% */
/* old kversion @(#)STNmedburst.mod	1.8 --- 08/05/99 -- 13:56:40 : jversion  @(#)STNmedburst.mod	1.2---04/23/99--18:39:50 */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

//
// STNmedburst
//
/**
 * STNmedburst class
 * Represents the Subthalamic Nucleus Burst Cells Layer
 * @see     STNmedburst
 * @version 0.1 96/11/19
 * @author Michael Crowley
 * -var private GPEmedburst_in - input coming from GPEmedburst module (of type NslDouble2)<p>
 * -var private STNmedburst_out - output going to SNRmedburst module (of type NslDouble2)<p>
 */

 public class STNmedburst extends NslModule /*(int CorticalArraySize)*/ {

  public NslDinDouble2 GPEmedburst_in ; /*(CorticalArraySize,CorticalArraySize) */  

  public NslDoutDouble2 STNmedburst_out ; /*(CorticalArraySize,CorticalArraySize) */  

  // private variables


  private  double stnmedbursttm;
  private  double STNmedburstTONIC;
  private  double STNlbsigma1;
  private  double STNlbsigma2;
  private  double STNlbsigma3;
  private  double STNlbsigma4;
  NslDouble2 stnmedburst ; /* (CorticalArraySize,CorticalArraySize)   */
  
   public  void initRun () {
    STNmedburst_out.set(0);
    stnmedbursttm = 0.01;
    STNmedburstTONIC = 60;
    STNlbsigma1 = 10; //20;
    STNlbsigma2 = 60;
    STNlbsigma3 = 0;
    STNlbsigma4 = 60;
  }
  public  void simRun () {
	  // System.err.println("@@@@ STNmedburst simRun entered @@@@");
    stnmedburst.set(system.nsldiff.eval(stnmedburst,stnmedbursttm,
 __nsltmp103=nslj.src.math.NslSub.eval(__nsltmp103,
 __nsltmp102=nslj.src.math.NslAdd.eval(__nsltmp102,
 __nsltmp101=nslj.src.math.NslSub.eval(__nsltmp101,0,stnmedburst.get()),STNmedburstTONIC),GPEmedburst_in.get()))) /* rule 108 */;
    STNmedburst_out.set(Nsl2Sigmoid.eval(stnmedburst,STNlbsigma1,STNlbsigma2,STNlbsigma3,STNlbsigma4)) /* rule 108 */;
  }

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	__nsltmp101 = new double[1][1];
	__nsltmp102 = new double[1][1];
	__nsltmp103 = new double[1][1];
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	for (int i = 0; i < __nsltmp101.length; i++) {
		for (int j = 0; j < __nsltmp101[0].length; j++) {
			__nsltmp101[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp102.length; i++) {
		for (int j = 0; j < __nsltmp102[0].length; j++) {
			__nsltmp102[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp103.length; i++) {
		for (int j = 0; j < __nsltmp103[0].length; j++) {
			__nsltmp103[i][j] = 0;
		}
	}
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	private  double[][] __nsltmp101;
	private  double[][] __nsltmp102;
	private  double[][] __nsltmp103;
	/* constructor and related methods */
	/* nsl declarations */
	int CorticalArraySize;

	 /*GENERIC CONSTRUCTOR:   */
	 public STNmedburst(String nslName, NslModule nslParent,int CorticalArraySize) {
		super(nslName, nslParent);
		this.CorticalArraySize = CorticalArraySize;
		initSys();
		makeInst(nslName, nslParent,CorticalArraySize);
	}
	public void makeInst(String nslName, NslModule nslParent,int CorticalArraySize){ 
	 GPEmedburst_in=new NslDinDouble2 ("GPEmedburst_in",this,CorticalArraySize,CorticalArraySize); //NSLDECLS 
	 STNmedburst_out=new NslDoutDouble2 ("STNmedburst_out",this,CorticalArraySize,CorticalArraySize); //NSLDECLS 
	 stnmedburst=new NslDouble2 ("stnmedburst",this,CorticalArraySize,CorticalArraySize); //NSLDECLS 
	}
	/* end of automatic declaration statements */
} //end class
