/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS  %W%---%G%--%U% */
/* old kversion @(#)ThFEFmem.mod	1.8 --- 08/05/99 -- 13:56:44 : jversion  @(#)ThFEFmem.mod	1.2---04/23/99--18:39:52 */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

//
//Module ThFEFmem - Part of the Thalamus
//
 public class ThFEFmem extends NslModule/*(int array_size)*/{
//input ports
    public NslDinDouble2 FEFmem_in ; /*(array_size,array_size)  */
    public NslDinDouble2 SNRmedburst_in ; /*(array_size,array_size) */
    public NslDinDouble2 ThMEDlcn_in ; /*(array_size,array_size)*/

//output ports
    public NslDoutDouble2 ThFEFmem_out ; /*(array_size,array_size)  */

  //private variables

  private  double Thfefmemtm;
  private  double ThfefmemK1;
  private  double ThfefmemK2;
  private  double ThfefmemK3;
  private  double ThFEFmemsigma1;
  private  double ThFEFmemsigma2;
  private  double ThFEFmemsigma3;
  private  double ThFEFmemsigma4;
   private NslDouble2 THNewActivation ; /*(array_size,array_size)*/

    private NslDouble2 Thfefmem ; /*(array_size,array_size)  */



public  void initModule()
 {
    THNewActivation.set((NslDouble2)nslGetValue("crowleyTop.thal1.THNewActivation")) /*rule 114 */;
  }

public  void initRun(){

    ThFEFmem_out.set(0);
    Thfefmem.set(0);
    Thfefmemtm=0.006;
    ThfefmemK1=1.5;
    ThfefmemK2=0.5;
    ThfefmemK3=0.5;
    ThFEFmemsigma1=30;
    ThFEFmemsigma2=65;
    ThFEFmemsigma3=0;
    ThFEFmemsigma4=60;
  }

public  void simRun(){
  /* <Q> FEFmem_in  SNRmedburst_in  ThMEDlcn_in  THNewActivation*/

  // System.err.println("@@@@ ThFEFmem simRun entered @@@@");
    Thfefmem.set(system.nsldiff.eval(Thfefmem,Thfefmemtm,
 __nsltmp108=nslj.src.math.NslAdd.eval(__nsltmp108,
 __nsltmp107=nslj.src.math.NslSub.eval(__nsltmp107,
 __nsltmp105=nslj.src.math.NslSub.eval(__nsltmp105,
 __nsltmp103=nslj.src.math.NslAdd.eval(__nsltmp103,
 __nsltmp101=nslj.src.math.NslSub.eval(__nsltmp101,0,Thfefmem.get()),
 __nsltmp102=nslj.src.math.NslElemMult.eval(__nsltmp102,ThfefmemK1,FEFmem_in.get())),
 __nsltmp104=nslj.src.math.NslElemMult.eval(__nsltmp104,ThfefmemK2,SNRmedburst_in.get())),
 __nsltmp106=nslj.src.math.NslElemMult.eval(__nsltmp106,ThfefmemK3,ThMEDlcn_in.get())),THNewActivation.get()))) /* rule 108 */;


   ThFEFmem_out.set(Nsl2Sigmoid.eval(Thfefmem,ThFEFmemsigma1,ThFEFmemsigma2,ThFEFmemsigma3,ThFEFmemsigma4)) /* rule 108 */;

	// 96/12/20
	//System.out.println("ThFEFmem_out: " + ThFEFmem_out);
  }

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	__nsltmp101 = new double[1][1];
	__nsltmp102 = new double[1][1];
	__nsltmp103 = new double[1][1];
	__nsltmp104 = new double[1][1];
	__nsltmp105 = new double[1][1];
	__nsltmp106 = new double[1][1];
	__nsltmp107 = new double[1][1];
	__nsltmp108 = new double[1][1];
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	for (int i = 0; i < __nsltmp101.length; i++) {
		for (int j = 0; j < __nsltmp101[0].length; j++) {
			__nsltmp101[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp102.length; i++) {
		for (int j = 0; j < __nsltmp102[0].length; j++) {
			__nsltmp102[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp103.length; i++) {
		for (int j = 0; j < __nsltmp103[0].length; j++) {
			__nsltmp103[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp104.length; i++) {
		for (int j = 0; j < __nsltmp104[0].length; j++) {
			__nsltmp104[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp105.length; i++) {
		for (int j = 0; j < __nsltmp105[0].length; j++) {
			__nsltmp105[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp106.length; i++) {
		for (int j = 0; j < __nsltmp106[0].length; j++) {
			__nsltmp106[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp107.length; i++) {
		for (int j = 0; j < __nsltmp107[0].length; j++) {
			__nsltmp107[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp108.length; i++) {
		for (int j = 0; j < __nsltmp108[0].length; j++) {
			__nsltmp108[i][j] = 0;
		}
	}
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	private  double[][] __nsltmp101;
	private  double[][] __nsltmp102;
	private  double[][] __nsltmp103;
	private  double[][] __nsltmp104;
	private  double[][] __nsltmp105;
	private  double[][] __nsltmp106;
	private  double[][] __nsltmp107;
	private  double[][] __nsltmp108;
	/* constructor and related methods */
	/* nsl declarations */
	int array_size;

	 /*GENERIC CONSTRUCTOR:   */
	 public ThFEFmem(String nslName, NslModule nslParent,int array_size) {
		super(nslName, nslParent);
		this.array_size = array_size;
		initSys();
		makeInst(nslName, nslParent,array_size);
	}
	public void makeInst(String nslName, NslModule nslParent,int array_size){ 
	 FEFmem_in=new NslDinDouble2 ("FEFmem_in",this,array_size,array_size); //NSLDECLS 
	 SNRmedburst_in=new NslDinDouble2 ("SNRmedburst_in",this,array_size,array_size); //NSLDECLS 
	 ThMEDlcn_in=new NslDinDouble2 ("ThMEDlcn_in",this,array_size,array_size); //NSLDECLS 
	 ThFEFmem_out=new NslDoutDouble2 ("ThFEFmem_out",this,array_size,array_size); //NSLDECLS 
	 THNewActivation=new NslDouble2 ("THNewActivation",this,array_size,array_size); //NSLDECLS 
	 Thfefmem=new NslDouble2 ("Thfefmem",this,array_size,array_size); //NSLDECLS 
	}
	/* end of automatic declaration statements */
} //end class
