/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS  %W%---%G%--%U% */
/* old kversion @(#)ThLIPmem.mod	1.8 --- 08/05/99 -- 13:56:45 : jversion  @(#)ThLIPmem.mod	1.2---04/23/99--18:34:25 */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

//
//Module ThLIPmem - parth of the Thalamus
//

 public class ThLIPmem extends NslModule/*(int array_size)*/ {
	//inputs
    public NslDinDouble2 LIPmem_in ; /*(array_size,array_size)    */
    public NslDinDouble2 SNRmedburst_in ; /*(array_size,array_size)    */
    public NslDinDouble2 ThMEDlcn_in ; /*(array_size,array_size)     */
	//outputs
    public NslDoutDouble2 ThLIPmem_out ; /*(array_size,array_size)  */
    public NslDoutDouble2 THNA_out ; /*(array_size,array_size)*/

  //privates
  private  double   Thlipmemtm;
  private  double   ThlipmemK1;
  private  double   ThlipmemK2;
  private  double   ThlipmemK3;
  private  double   ThLIPmemsigma1;
  private  double   ThLIPmemsigma2;
  private  double   ThLIPmemsigma3;
  private  double   ThLIPmemsigma4;

 private   NslDouble2 Thlipmem ; /*(array_size,array_size)   */
    // envs
  private  NslDouble2 THNewActivation ; /*(array_size,array_size)   */


public  void initModule(){
   THNewActivation.set((NslDouble2)nslGetValue("crowleyTop.thal1.THNewActivation")) /*rule 114 */;


   //System.out.println("\n\n``````````````````````` THNewActivation:"+THNewActivation+"\n\n");
}

public  void initRun(){
     ThLIPmem_out.set(0);
     Thlipmem.set(0);

     Thlipmemtm=0.006;
     ThlipmemK1=1.5;
     ThlipmemK2=0.5;
     ThlipmemK3=0.5;
     ThLIPmemsigma1=30;
     ThLIPmemsigma2=65;
     ThLIPmemsigma3=0;
     ThLIPmemsigma4=60;
     THNA_out.set(THNewActivation);
}

public  void simRun(){
  /* <Q> LIPmem_in SNRmedburst_in ThMEDlcn_in THNewActivation */

  // System.err.println("@@@@ ThLIPmem simRun entered @@@@");

     THNA_out.set(THNewActivation);
//System.err.println("THNEWACT:"+THNewActivation);
    Thlipmem.set(system.nsldiff.eval(Thlipmem,Thlipmemtm,
 __nsltmp108=nslj.src.math.NslAdd.eval(__nsltmp108,
 __nsltmp107=nslj.src.math.NslSub.eval(__nsltmp107,
 __nsltmp105=nslj.src.math.NslSub.eval(__nsltmp105,
 __nsltmp103=nslj.src.math.NslAdd.eval(__nsltmp103,
 __nsltmp101=nslj.src.math.NslSub.eval(__nsltmp101,0,Thlipmem.get()),
 __nsltmp102=nslj.src.math.NslElemMult.eval(__nsltmp102,ThlipmemK1,LIPmem_in.get())),
 __nsltmp104=nslj.src.math.NslElemMult.eval(__nsltmp104,ThlipmemK2,SNRmedburst_in.get())),
 __nsltmp106=nslj.src.math.NslElemMult.eval(__nsltmp106,ThlipmemK3,ThMEDlcn_in.get())),THNewActivation.get()))) /* rule 108 */;

   ThLIPmem_out.set(Nsl2Sigmoid.eval(Thlipmem,ThLIPmemsigma1,ThLIPmemsigma2,ThLIPmemsigma3,ThLIPmemsigma4)) /* rule 108 */;
  }

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	__nsltmp101 = new double[1][1];
	__nsltmp102 = new double[1][1];
	__nsltmp103 = new double[1][1];
	__nsltmp104 = new double[1][1];
	__nsltmp105 = new double[1][1];
	__nsltmp106 = new double[1][1];
	__nsltmp107 = new double[1][1];
	__nsltmp108 = new double[1][1];
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	for (int i = 0; i < __nsltmp101.length; i++) {
		for (int j = 0; j < __nsltmp101[0].length; j++) {
			__nsltmp101[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp102.length; i++) {
		for (int j = 0; j < __nsltmp102[0].length; j++) {
			__nsltmp102[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp103.length; i++) {
		for (int j = 0; j < __nsltmp103[0].length; j++) {
			__nsltmp103[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp104.length; i++) {
		for (int j = 0; j < __nsltmp104[0].length; j++) {
			__nsltmp104[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp105.length; i++) {
		for (int j = 0; j < __nsltmp105[0].length; j++) {
			__nsltmp105[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp106.length; i++) {
		for (int j = 0; j < __nsltmp106[0].length; j++) {
			__nsltmp106[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp107.length; i++) {
		for (int j = 0; j < __nsltmp107[0].length; j++) {
			__nsltmp107[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp108.length; i++) {
		for (int j = 0; j < __nsltmp108[0].length; j++) {
			__nsltmp108[i][j] = 0;
		}
	}
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	private  double[][] __nsltmp101;
	private  double[][] __nsltmp102;
	private  double[][] __nsltmp103;
	private  double[][] __nsltmp104;
	private  double[][] __nsltmp105;
	private  double[][] __nsltmp106;
	private  double[][] __nsltmp107;
	private  double[][] __nsltmp108;
	/* constructor and related methods */
	/* nsl declarations */
	int array_size;

	 /*GENERIC CONSTRUCTOR:   */
	 public ThLIPmem(String nslName, NslModule nslParent,int array_size) {
		super(nslName, nslParent);
		this.array_size = array_size;
		initSys();
		makeInst(nslName, nslParent,array_size);
	}
	public void makeInst(String nslName, NslModule nslParent,int array_size){ 
	 LIPmem_in=new NslDinDouble2 ("LIPmem_in",this,array_size,array_size); //NSLDECLS 
	 SNRmedburst_in=new NslDinDouble2 ("SNRmedburst_in",this,array_size,array_size); //NSLDECLS 
	 ThMEDlcn_in=new NslDinDouble2 ("ThMEDlcn_in",this,array_size,array_size); //NSLDECLS 
	 ThLIPmem_out=new NslDoutDouble2 ("ThLIPmem_out",this,array_size,array_size); //NSLDECLS 
	 THNA_out=new NslDoutDouble2 ("THNA_out",this,array_size,array_size); //NSLDECLS 
	 Thlipmem=new NslDouble2 ("Thlipmem",this,array_size,array_size); //NSLDECLS 
	 THNewActivation=new NslDouble2 ("THNewActivation",this,array_size,array_size); //NSLDECLS 
	}
	/* end of automatic declaration statements */
} //end class
