/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS  %W%---%G%--%U% */
/* old kversion @(#)ThMEDlcn.mod	1.8 --- 08/05/99 -- 13:56:45 : jversion  @(#)ThMEDlcn.mod	1.2---04/23/99--18:33:45 */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

//
//Module ThMEDlcn - part of Thalamus
//

 public class ThMEDlcn extends NslModule/*(int array_size)*/{
//inputs
    public NslDinDouble2 RNMEDinh_in ; /*(array_size,array_size)  */
//outputs
    public NslDoutDouble2 ThMEDlcn_out ; /*(array_size,array_size)  */

	private  double    Thmedlcntm;
	private  double    ThmedlcnTONIC;
	private  double    ThmedlcnK;
	private  double    ThMEDlcnsigma1;
	private  double    ThMEDlcnsigma2;
	private  double    ThMEDlcnsigma3;
	private  double    ThMEDlcnsigma4;
	private NslDouble2 Thmedlcn ; /*(array_size,array_size)   */
  
public  void initRun(){
    Thmedlcn.set(0);
    ThMEDlcn_out.set(0);

     Thmedlcntm=0.006;
     ThmedlcnTONIC=10; ThmedlcnK=1;
     ThMEDlcnsigma1=-10;
     ThMEDlcnsigma2=10;
     ThMEDlcnsigma3=0;
     ThMEDlcnsigma4=10;
}

public  void simRun(){
	  /* <Q> RNMEDinh_in */
      // System.err.println("@@@@ ThMEDlcn simRun entered @@@@");
    Thmedlcn.set(system.nsldiff.eval(Thmedlcn,Thmedlcntm,
 __nsltmp104=nslj.src.math.NslSub.eval(__nsltmp104,
 __nsltmp102=nslj.src.math.NslAdd.eval(__nsltmp102,
 __nsltmp101=nslj.src.math.NslSub.eval(__nsltmp101,0,Thmedlcn.get()),ThmedlcnTONIC),
 __nsltmp103=nslj.src.math.NslElemMult.eval(__nsltmp103,ThmedlcnK,RNMEDinh_in.get())))) /* rule 108 */;

    ThMEDlcn_out.set(Nsl2Sigmoid.eval(Thmedlcn,ThMEDlcnsigma1,ThMEDlcnsigma2,ThMEDlcnsigma3,ThMEDlcnsigma4)) /* rule 108 */;
  }

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	__nsltmp101 = new double[1][1];
	__nsltmp102 = new double[1][1];
	__nsltmp103 = new double[1][1];
	__nsltmp104 = new double[1][1];
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	for (int i = 0; i < __nsltmp101.length; i++) {
		for (int j = 0; j < __nsltmp101[0].length; j++) {
			__nsltmp101[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp102.length; i++) {
		for (int j = 0; j < __nsltmp102[0].length; j++) {
			__nsltmp102[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp103.length; i++) {
		for (int j = 0; j < __nsltmp103[0].length; j++) {
			__nsltmp103[i][j] = 0;
		}
	}
	for (int i = 0; i < __nsltmp104.length; i++) {
		for (int j = 0; j < __nsltmp104[0].length; j++) {
			__nsltmp104[i][j] = 0;
		}
	}
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	private  double[][] __nsltmp101;
	private  double[][] __nsltmp102;
	private  double[][] __nsltmp103;
	private  double[][] __nsltmp104;
	/* constructor and related methods */
	/* nsl declarations */
	int array_size;

	 /*GENERIC CONSTRUCTOR:   */
	 public ThMEDlcn(String nslName, NslModule nslParent,int array_size) {
		super(nslName, nslParent);
		this.array_size = array_size;
		initSys();
		makeInst(nslName, nslParent,array_size);
	}
	public void makeInst(String nslName, NslModule nslParent,int array_size){ 
	 RNMEDinh_in=new NslDinDouble2 ("RNMEDinh_in",this,array_size,array_size); //NSLDECLS 
	 ThMEDlcn_out=new NslDoutDouble2 ("ThMEDlcn_out",this,array_size,array_size); //NSLDECLS 
	 Thmedlcn=new NslDouble2 ("Thmedlcn",this,array_size,array_size); //NSLDECLS 
	}
	/* end of automatic declaration statements */
} //end class
