
/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;

/*********************************/

public class MaxSelector extends NslModule {

//NSL Version: 3_0_n
//Sif Version: 6
//libNickName: booklib
//moduleName:  MaxSelector
//versionName: 1_1_1
//floatSubModules: true


//variables 
private  Ulayer u1; // This is the main module within the model
private  Vlayer v1; // 

public  NslDinDouble1 in; // 
public  NslDoutDouble1 out; // 

//methods 
public void makeConn(){
    nslConnect(this.in, u1.s_in);
    nslConnect(v1.vf, u1.v_in);
    nslConnect(u1.uf, v1.u_in);
    nslConnect(u1.uf, this.out);
}

	/******************************************************/
	/*                                                    */
	/* Generated by NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int size;

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public MaxSelector(String nslName, NslModule nslParent, int size) {
		super(nslName, nslParent);
		this.size=size;
		initSys();
		makeInst(nslName, nslParent, size);
	}

	public void makeInst(String nslName, NslModule nslParent, int size) { 
		callFromConstructorTop();
		u1 = new Ulayer("u1", this, size);
		v1 = new Vlayer("v1", this);
		in = new NslDinDouble1("in", this, size);
		out = new NslDoutDouble1("out", this, size);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}//end MaxSelector

