

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;

/*********************************/

public class Ulayer extends NslModule{

//NSL Version: 3_0_n
//Sif Version: 6
//libNickName: booklib
//moduleName:  Ulayer
//versionName: 1_1_1
//floatSubModules: true


//variables 
public  NslDinDouble1 s_in; // This is the source input for the module
public  NslDinDouble0 v_in; // Feedback input

public  NslDoutDouble1 uf; // Firing rate output from module Ulayer.

private  NslDouble0 h1; // 
private  NslDouble1 up; // 

//methods 
public void initModule() {
	uf.set(0);
}

public void initRun() {
	uf.set(0);
	up.set(0);
	h1.set(0.1);
}

public void simRun(){
	up.set(  system.nsldiff.eval(up, __temp4.setReference(NslAdd.eval(__temp4.get(), __temp3.setReference(NslSub.eval(__temp3.get(), __temp2.setReference(NslSub.eval(__temp2.get(), __temp1.setReference(NslAdd.eval(__temp1.get(), __temp0.setReference(NslSub.eval(__temp0.get(), 0, up)), uf)), v_in)), h1)), s_in)) ));
	uf.set(  NslStep.eval(up,0.1,0,1.0));
}


	/******************************************************/
	/*                                                    */
	/* Generated by NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int size;

	/* Temporary variables */
		NslDouble1 __temp0 = new NslDouble1(1);
		NslDouble1 __temp1 = new NslDouble1(1);
		NslDouble1 __temp2 = new NslDouble1(1);
		NslDouble1 __temp3 = new NslDouble1(1);
		NslDouble1 __temp4 = new NslDouble1(1);

	/* GENERIC CONSTRUCTOR: */
	public Ulayer(String nslName, NslModule nslParent, int size) {
		super(nslName, nslParent);
		this.size=size;
		initSys();
		makeInst(nslName, nslParent, size);
	}

	public void makeInst(String nslName, NslModule nslParent, int size) { 
		callFromConstructorTop();
		s_in = new NslDinDouble1("s_in", this);
		v_in = new NslDinDouble0("v_in", this);
		uf = new NslDoutDouble1("uf", this, size);
		h1 = new NslDouble0("h1", this);
		up = new NslDouble1("up", this, size);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/



}//end Ulayer

