/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS %W%---%G%--%U% */

/* Copyright 1999 University of Southern California Brain Lab */
/* Author Jacob Spoelstra */
/* email nsl@java.usc.edu */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

 public class IO_layer extends NslModule/*()*/ {
    // constants
    static final  double f_max  = 10.;
    static final  double offset = 1.3865;  // gives output of 2 for 0 input
    static final  double slope  = 1.;
    // inports
    NslDinDouble1 sens_in ; /*(2)*/  // SENS input
    NslDinDouble1 nuc_in ; /*(2)*/   // NUC input
    // outports
    NslDoutDouble1 io_out ; /*(2)*/ 
    // variables
    NslDouble1 io_mp ; /*(2)*/
  
 public  void initModule() {
     io_out.set(2.);
 }
  
 public  void simTrain() {
     simRun();
 }
  
 public  void simRun(){
      double nuc_act;

     nuc_act=NslSumRows.eval(nuc_in)/* rule 102*/;
     io_mp.set(
 __nsltmp101=nslj.src.math.NslSub.eval(__nsltmp101,sens_in.get(),(.01)*(nuc_act)));
     io_out.set(
 __nsltmp102=nslj.src.math.NslElemMult.eval(__nsltmp102,f_max,NslSigmoid.eval(io_mp,slope,offset)));
 }
	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	__nsltmp101 = new double[1];
	__nsltmp102 = new double[1];
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	for (int i = 0; i < __nsltmp101.length; i++) {
		__nsltmp101[i] = 0;
}
	for (int i = 0; i < __nsltmp102.length; i++) {
		__nsltmp102[i] = 0;
}
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	private  double[] __nsltmp101;
	private  double[] __nsltmp102;
	/* constructor and related methods */
	/* nsl declarations */

	 /*GENERIC CONSTRUCTOR:   */
	 public IO_layer(String nslName, NslModule nslParent) {
		super(nslName, nslParent);
		initSys();
		makeInst(nslName, nslParent);
	}
	public void makeInst(String nslName, NslModule nslParent){ 
	 sens_in=new NslDinDouble1 ("sens_in",this,2); //NSLDECLS 
	 nuc_in=new NslDinDouble1 ("nuc_in",this,2); //NSLDECLS 
	 io_out=new NslDoutDouble1 ("io_out",this,2); //NSLDECLS 
	 io_mp=new NslDouble1 ("io_mp",this,2); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
