/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS %W%---%G%--%U% */

/* Copyright 1999 University of Southern California Brain Lab */
/* Author Jacob Spoelstra */
/* email nsl@java.usc.edu */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

 public class PP_layer extends NslModule/*()*/ {
    // constants
    static final  double sx2 = 12.25; // 3.5*3.5
    static final  double sy2 = 9.;    // 3*3
    // inports
    // outports
    NslDoutDouble0 s_out ; /*()*/    // Strategy: [0:1] over/under 
    NslDoutDouble2 pp_out ; /*(10,10)*/ // PP population coding
    // variables
    NslDouble0 a_out ; /*()*/       // Aim direction [-30:30]
    NslDouble0 pp_noise ; /*()*/
    NslDouble0 pp_sep ; /*()*/

 public  void initModule(){
     pp_noise.set((NslDouble0)nslGetValue("dartModel.pp_noise")) /*rule 114 */;
     pp_sep.set((NslDouble0)nslGetValue("dartModel.pp_sep")) /*rule 114 */;
 }
 
 public  void simTrain() {
     simRun();
 }
 
 public  void simRun(){
      int i,j;
      double mx, my;
      double dx,dy;

     s_out.set((NslDouble0)nslGetValue("dartModel.s_out")) /*rule 114 */;
     a_out.set((NslDouble0)nslGetValue("dartModel.d_out")) /*rule 114 */;
     
     my=(4.5)+((
 nslj.src.math.NslElemMult.eval(NslStep.eval(s_out,.5,-(1),1),pp_sep.get()))/(2.)); // throw = over/under
     mx=(4.5)+((
 nslj.src.math.NslElemMult.eval(4.5,a_out.get()))/(30.));
     
     for(i=0;i<10;i++){
	 dx = mx - i;
	 for(j=0;j<10;j++){
	     dy = my - j;
	     (pp_out).set(i,j,((pp_noise.get())*(NslRandom.eval()))+(((1.)-(pp_noise.get()))*(NslOperator.exp.eval((-(1.))*((((dx)*(dx))/(sx2))+(((dy)*(dy))/(sy2)))))));
	 }
     }
 }
	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */

	 /*GENERIC CONSTRUCTOR:   */
	 public PP_layer(String nslName, NslModule nslParent) {
		super(nslName, nslParent);
		initSys();
		makeInst(nslName, nslParent);
	}
	public void makeInst(String nslName, NslModule nslParent){ 
	 s_out=new NslDoutDouble0 ("s_out",this); //NSLDECLS 
	 pp_out=new NslDoutDouble2 ("pp_out",this,10,10); //NSLDECLS 
	 a_out=new NslDouble0 ("a_out",this); //NSLDECLS 
	 pp_noise=new NslDouble0 ("pp_noise",this); //NSLDECLS 
	 pp_sep=new NslDouble0 ("pp_sep",this); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
