/* SCCS  %W--- %G% -- %U% */
//
// MaxSelectorStimulus
//
//////////////////////////////////////////////////////////////////////

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;

/*********************************/

public class MaxSelectorStimulus extends NslModule {

    public  NslDoutDouble1 s_out;

    public void initRun() {
	s_out.set(0);
	s_out.set(1, 0.5);
	s_out.set(3, 1.0);
    }

	/******************************************************/
	/*                                                    */
	/* Generated by NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int size;

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public MaxSelectorStimulus(String nslName, NslModule nslParent, int size) {
		super(nslName, nslParent);
		this.size=size;
		initSys();
		makeInst(nslName, nslParent, size);
	}

	public void makeInst(String nslName, NslModule nslParent, int size) { 
		callFromConstructorTop();
		s_out = new NslDoutDouble1("s_out", this, size);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/


}







