/* SCCS @(#)MaxSelector.mod	1.2 --- 09/20/99 -- 21:15:36 */
//
// MaxSelector for MaxSelectorModel
//
////////////////////////////////////////////////////////////

/*********************************/
/*                               */
/*   Importing all Nsl classes   */
/*                               */
/*********************************/

import nslj.src.system.*;
import nslj.src.cmd.*;
import nslj.src.lang.*;
import nslj.src.math.*;
import nslj.src.display.*;

/*********************************/

public class MaxSelector extends NslModule {

    public  NslDinDouble1 in;
    public  NslDoutDouble1 out;

    private  Ulayer u1;  
    private  Vlayer v1;                   

    public void makeConn() {
	nslConnect(this.in, u1.s_in); 
	nslConnect(u1.uf, v1.u_in); 
	nslConnect(v1.vf, u1.v_in); 
	nslConnect(u1.uf, this.out);
    }


	/******************************************************/
	/*                                                    */
	/* Generated by NslCompiler. Do not edit these lines! */
	/*                                                    */
	/******************************************************/

	/* Constructor and related methods */
	/* makeinst() declared variables */

	/* Formal parameters */
	int size;

	/* Temporary variables */

	/* GENERIC CONSTRUCTOR: */
	public MaxSelector(String nslName, NslModule nslParent, int size) {
		super(nslName, nslParent);
		this.size=size;
		initSys();
		makeInst(nslName, nslParent, size);
	}

	public void makeInst(String nslName, NslModule nslParent, int size) { 
		callFromConstructorTop();
		in = new NslDinDouble1("in", this, size);
		out = new NslDoutDouble1("out", this, size);
		u1 = new Ulayer("u1", this, size);
		v1 = new Vlayer("v1", this);
		callFromConstructorBottom();
	}

	/******************************************************/
	/*                                                    */
	/* End of automatic declaration statements.           */
	/*                                                    */
	/******************************************************/



}

