/* This file is generated by  NSL3.0 preprocessor*/

/* SCCS @(#)HillclimbTop.mod	1.1 --- 09/24/99 -- 16:05:43 */
/* Copyright 1999 University of Southern California Brain Lab */
/* Author: Mihai Bota */
/* email nsl@java.usc.edu */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

 public class HillclimbTop extends NslModel/*()*/ {
        private  int weightSize=4;
        private  int arraySize=40;

	private HillclimbCalc calc ; /*(weightSize,arraySize)*/
	private HillOut out ; /*(weightSize,arraySize)*/

	private  double ttime;
	private  double rtime;

	public  void initSys (){
		//system.setEndTime(800.0);
		system.setTrainEndTime(500.0);
		system.nslSetTrainDelta(1.0);
		system.setRunEndTime(300.0);
		system.nslSetRunDelta(1.0);
	}
	public  void makeConn() {
		nslConnect(calc.x,out.x);
		nslConnect(calc.y,out.y);
		nslConnect(calc.distance,out.distance);
		nslConnect(calc.Weight,out.Weight);
		nslConnect(calc.areaTrain,out.areaTrain);
		nslConnect(calc.areaRun,out.areaRun);
	}
	public  void initModule() {
		nslSetRunDelta(1.0);
		nslSetTrainDelta(1.0);
	}

	public  void simTrain() {
		if (system.debug>1 ) {
			ttime=system.getCurrentTime()/* rule 102*/;
			System.out.println(("Top:simTrain:")+(ttime));
		}
	}
	public  void simRun() {	
		if (system.debug>1 ) {
			rtime=system.getCurrentTime()/* rule 102*/;
			System.out.println(("Top:simRun:")+(rtime));
		}

	}
	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* EMPTY CONSTRUCTOR: Called only for the top level module */
	 public HillclimbTop() {
		super("hillclimbTop",(NslModel)null);
		if (NslMain.TopLoaded) { System.err.println(
		 "ERROR: construction without (name,parent)");
		 System.exit(1);} 
		 NslMain.TopLoaded=true; 
		initSys();
		makeInst("hillclimbTop",null);
	}
	/* nsl declarations */

	 /*GENERIC CONSTRUCTOR:   */
	 public HillclimbTop(String nslName, NslModule nslParent) {
		super(nslName, nslParent);
		initSys();
		makeInst(nslName, nslParent);
	}
	public void makeInst(String nslName, NslModule nslParent){ 
	 calc=new HillclimbCalc ("calc",this,weightSize,arraySize); //NSLDECLS 
	 out=new HillOut ("out",this,weightSize,arraySize); //NSLDECLS 
	}
	/* end of automatic declaration statements */
} //end class
